apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: beer-rec-pvc
spec:
  storageClassName: ovirt-csi-sc
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
  volumeMode: Filesystem