apiVersion: v1
kind: Pod
metadata:
  labels:
    run: busybox
  name: postsync
  annotations:
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
    argocd.argoproj.io/sync-wave: "0"
spec:
  containers:
  - args:
    - /bin/sh
    - -c
    - sleep 15; echo "hello world post sync"
    image: busybox
    name: busybox
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}