# Topics

apiVersion: kafka.strimzi.io/v1beta1
kind: KafkaTopic
metadata:
  name: http-messages
  namespace: beer-rec-system
  labels:
    strimzi.io/cluster: my-cluster
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  partitions: 1
  replicas: 1