apiVersion: v1
kind: Pod
metadata:
  name: jumpbox
spec:
  containers:
    - name: jumpbox
      image: ubuntu:latest
      command: ["/bin/sh", "-c", "tail -f /dev/null"]
      volumeMounts:
      - mountPath: "/mnt/storage"
        name: storage
  volumes:
    - name: storage
      persistentVolumeClaim:
        claimName: beer-rec-pvc
