apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: 00-install-operators
  namespace: openshift-gitops
spec:
  destination:
    server: {{ .Values.spec.destination.server }}
    namespace: openshift-operators
  source:
    repoURL: 'https://github.com/beer-horoscope/beer-horoscope.git'
    path: operators
    targetRevision: HEAD
  project: default
  syncPolicy:
    syncOptions:
      - CreateNamespace=true