apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: install-operators
  namespace: openshift-gitops
spec:
  destination:
    server: {{ .Values.spec.destination.server }}
    namespace: openshift-operators
  source:
    repoURL: 'https://gitlab.consulting.redhat.com/kelee/chicago-red-hat-summit-ai-ml.git'
    path: operators
    targetRevision: HEAD
  project: default
  syncPolicy:
    syncOptions:
      - CreateNamespace=true