apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: 02-odh
  namespace: openshift-gitops
spec:
  destination:
    server: {{ .Values.spec.destination.server }}
    namespace: beer-rec-system
  source:
    repoURL: 'https://github.com/beer-horoscope/beer-horoscope.git'
    path: infra/02-odh
    targetRevision: smaller-footprint
  project: default
  syncPolicy:
    syncOptions:
      - CreateNamespace=true