apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: modify-pods
  annotations:
    argocd.argoproj.io/sync-wave: "1"
rules:
  - verbs:
      - '*'
    apiGroups:
      - '*'
    resources:
      - '*'
