apiVersion: v1
kind: Pod
metadata:
  name: train-models-job
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  serviceAccountName: internal-oc-container
  volumes:
  - name: storage
    persistentVolumeClaim:
      claimName: beer-rec-pvc
  volumeMounts:
    - mountPath: "/mnt/storage"
      name: storage
  containers:
  - name: internal-oc-container
    image: quay.io/kelee/internal-oc-container:latest
    command:
    - sh
    - "-c"
    - |
      /bin/bash <<'EOF'

      cd /home
      mkdir temp
      cd temp
      git clone https://github.com/beer-horoscope/beer-horoscope.git
      cd beer-horoscope
      
      tail -f /dev/null
      EOF
  restartPolicy: Never
        