apiVersion: v1
kind: Pod
metadata:
  name: create-database-job
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  serviceAccountName: internal-oc-container
  containers:
  - name: internal-oc-container
    image: quay.io/kelee/internal-oc-container:latest
    command:
    - sh
    - "-c"
    - |
      /bin/bash <<'EOF'

      cd /home
      mkdir temp
      cd temp
      git clone https://github.com/beer-horoscope/beer-horoscope.git
      cd beer-horoscope
      git checkout smaller-footprint
      source scripts/create-database.sh
       
      EOF
  restartPolicy: Never
        
